[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "semgraph"
dynamic = ["version"]
description = ''
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
keywords = []
authors = [
    { name = "Yasas Senarath", email = "12231659+ysenarath@users.noreply.github.com" },
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
    "accelerate>=1.13.0",
    "amrlib>=0.8.1",
    "appdirs>=1.4.4",
    "cached-property>=2.0.1",
    "platformdirs>=4.9.6",
    "transformers>=4.20,<4.27",
    "unidecode>=1.4.0",
]

[project.urls]
Documentation = "https://github.com/ysenarath/semgraph#readme"
Issues = "https://github.com/ysenarath/semgraph/issues"
Source = "https://github.com/ysenarath/semgraph"

[tool.hatch.version]
path = "src/semgraph/__init__.py"

[tool.hatch.envs.types]
extra-dependencies = ["mypy>=1.0.0"]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/semgraph tests}"

[tool.coverage.run]
source_pkgs = ["semgraph", "tests"]
branch = true
parallel = true
omit = []

[tool.coverage.paths]
semgraph = ["src/semgraph", "*/semgraph/src/semgraph"]
tests = ["tests", "*/semgraph/tests"]

[tool.coverage.report]
exclude_lines = ["no cov", "if __name__ == .__main__.:", "if TYPE_CHECKING:"]
